/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.managers;

import java.sql.*;
import dal.Connection_Module;
import javax.swing.JOptionPane;

/**
 *
 * @author William
 */
public class StudentEnrol extends javax.swing.JInternalFrame {

    //All the connectors  must be used here again
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form StudentEnrol
     */
    public StudentEnrol() {
        initComponents();
        conn = Connection_Module.connector();
    }

    private void StdIDSearch() {
        String sql = "select * from users where StudentID=?";
        ;

        try {

            pst = conn.prepareStatement(sql);

            pst.setString(1, txtStdID.getText());
            //pst.setString(2, txtStdID.getText());

            rs = pst.executeQuery();

            if (rs.next()) {
                    
                txtStdNm.setText(rs.getString(3));
                //txtEmail.setText(rs.getString(3)); //here is where the second item of the table is 
                //txtPhn.setText(rs.getString(4)); //here is where the third item of the table is 
                //cboCourse.setSelectedItem(rs.getString(5)); //here is where the sixth item of the table is (combo box)
                cboBranch.setSelectedItem(rs.getString(6));

            }
            else{
                
                JOptionPane.showMessageDialog(null, "Student Not Found");
            }
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e);

        }

    }
    
    private void StdSearch() {
        String sql = "select * from student where StudentID=?";
        ;

        try {

            pst = conn.prepareStatement(sql);

            pst.setString(1, txtStdID.getText());
            //pst.setString(2, txtStdID.getText());

            rs = pst.executeQuery();

            if (rs.next()) {
                    
                txtStdNm.setText(rs.getString(2));
                txtEmail.setText(rs.getString(3)); //here is where the second item of the table is 
                txtPhn.setText(rs.getString(4)); //here is where the third item of the table is 
                cboCourse.setSelectedItem(rs.getString(5)); //here is where the sixth item of the table is (combo box)
                cboBranch.setSelectedItem(rs.getString(6));

            }else {
                
                JOptionPane.showMessageDialog(null, "Student Not Found");
            }
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e);

        }

    }

    private void UpdatingStudentDetails() {

        //Here the student data is updated into "student" table as the ID has been already set by the SuperUser "ADMIN"
        //Here by searching the student data by user is possible to add additional info such as email, phone, course and module.
        String sql = "Insert into student (Stud_Name, Stud_Email, Stud_Phone, CourseID, Branch) values (?, ?, ?, ?,?)";

        try {

            pst = conn.prepareStatement(sql);
            pst.setString(1, txtStdNm.getText());
            pst.setString(2, txtEmail.getText());
            pst.setString(3, txtPhn.getText());
            pst.setString(4, cboCourse.getSelectedItem().toString());
            pst.setString(5, cboBranch.getSelectedItem().toString());

            if (txtStdID.getText().isEmpty() || txtStdNm.getText().isEmpty() || txtEmail.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please fill all mandatory fields");
            } else {
                int added = pst.executeUpdate();
                if (added > 0) {//confirming the  addition of a data in the table
                    JOptionPane.showMessageDialog(null, "Student enrolled successfully");
                    txtStdID.setText(null);
                    txtStdNm.setText(null);
                    txtEmail.setText(null);
                    txtPhn.setText(null);
                    cboCourse.setSelectedItem(null);
                    cboBranch.setSelectedItem(null);
                    

                }
            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e);
        }
        ;
        //Java code
        ;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUpdateStd = new javax.swing.JButton();
        stdSearch = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtStdID = new javax.swing.JTextField();
        txtPhn = new javax.swing.JTextField();
        txtStdNm = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        cboCourse = new javax.swing.JComboBox<>();
        cboBranch = new javax.swing.JComboBox<>();
        stdIDCheck = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setMaximumSize(new java.awt.Dimension(480, 420));
        setPreferredSize(new java.awt.Dimension(480, 420));

        btnUpdateStd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update.jpg"))); // NOI18N
        btnUpdateStd.setToolTipText("Update Info");
        btnUpdateStd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateStdActionPerformed(evt);
            }
        });

        stdSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/StudSearch.png"))); // NOI18N
        stdSearch.setToolTipText("Search Student");
        stdSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdSearchActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Student ID");
        jLabel4.setPreferredSize(new java.awt.Dimension(7, 20));

        txtStdID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtStdID.setToolTipText("");
        txtStdID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStdIDActionPerformed(evt);
            }
        });

        txtPhn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPhn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhnActionPerformed(evt);
            }
        });

        txtStdNm.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtStdNm.setToolTipText("SudentID");
        txtStdNm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStdNmActionPerformed(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Email Address");
        jLabel7.setPreferredSize(new java.awt.Dimension(7, 20));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Student Full Name");
        jLabel3.setPreferredSize(new java.awt.Dimension(7, 20));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Student Phone");
        jLabel2.setPreferredSize(new java.awt.Dimension(7, 20));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Course Code");
        jLabel6.setPreferredSize(new java.awt.Dimension(7, 20));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Branch");
        jLabel5.setPreferredSize(new java.awt.Dimension(7, 20));

        txtEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        cboCourse.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cboCourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GVC1 Music", "GVC2 Maths", "GVC3 Computing", "GVC4 Law", "GV5 Engineering" }));
        cboCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCourseActionPerformed(evt);
            }
        });

        cboBranch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cboBranch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dublin", "Cork", "Galway" }));
        cboBranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboBranchActionPerformed(evt);
            }
        });

        stdIDCheck.setText("Search");
        stdIDCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdIDCheckActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtStdNm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPhn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(txtStdID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(stdIDCheck))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cboBranch, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(cboCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtStdID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stdIDCheck))
                        .addGap(18, 18, 18)
                        .addComponent(txtStdNm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPhn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboBranch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cboCourse, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, txtEmail, txtPhn, txtStdID, txtStdNm});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(stdSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addComponent(btnUpdateStd, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUpdateStd, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stdSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtStdNmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStdNmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStdNmActionPerformed

    private void txtStdIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStdIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStdIDActionPerformed

    private void txtPhnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhnActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void stdSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stdSearchActionPerformed
        // TODO add your handling code here:
        StdSearch();
    }//GEN-LAST:event_stdSearchActionPerformed

    private void btnUpdateStdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateStdActionPerformed
        // TODO add your handling code here:
        UpdatingStudentDetails();

    }//GEN-LAST:event_btnUpdateStdActionPerformed

    private void cboCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCourseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboCourseActionPerformed

    private void cboBranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboBranchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboBranchActionPerformed

    private void stdIDCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stdIDCheckActionPerformed
        StdIDSearch();
    }//GEN-LAST:event_stdIDCheckActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdateStd;
    private javax.swing.JComboBox<String> cboBranch;
    private javax.swing.JComboBox<String> cboCourse;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton stdIDCheck;
    private javax.swing.JButton stdSearch;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtPhn;
    private javax.swing.JTextField txtStdID;
    private javax.swing.JTextField txtStdNm;
    // End of variables declaration//GEN-END:variables

}
