/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import view.managers.StudentEnrol;
import view.lectuer.Test_ExamsScreen;
import view.managers.StaffRegistration;
import view.managers.Registration;
import view.students.StudentScreen;
import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import view.lectuer.ExamsScr;
import view.branches.FeesScreen;

/**
 *
 * @author William
 */
public class MainScreen extends javax.swing.JFrame {

    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        JmainPainel = new javax.swing.JInternalFrame();
        jInternalFrame3 = new javax.swing.JInternalFrame();
        UserID = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtPass = new javax.swing.JTextField();
        cboProfile = new javax.swing.JComboBox<>();
        btnAdd = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnDrop = new javax.swing.JButton();
        btnUpd = new javax.swing.JButton();
        JRegPan = new javax.swing.JInternalFrame();
        RegPan = new javax.swing.JPanel();
        jMenuBar2 = new javax.swing.JMenuBar();
        RegMenu = new javax.swing.JMenu();
        RegMenuTab = new javax.swing.JMenuItem();
        StaffReg = new javax.swing.JMenu();
        MenuStaffUpdate = new javax.swing.JMenuItem();
        MenuStaffUpdate1 = new javax.swing.JMenuItem();
        examMenu = new javax.swing.JMenu();
        AttendanceMenu = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        BranchMenu = new javax.swing.JMenu();
        DublinMenu = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        CorkMenu = new javax.swing.JMenu();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        feeCork = new javax.swing.JMenuItem();
        GalwayMenu = new javax.swing.JMenu();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMenuItem27 = new javax.swing.JMenuItem();
        GalwayMen = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jInternalFrame1.setClosable(true);
        jInternalFrame1.setIconifiable(true);
        jInternalFrame1.setMaximizable(true);
        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 384, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 414, Short.MAX_VALUE)
        );

        JmainPainel.setClosable(true);
        JmainPainel.setIconifiable(true);
        JmainPainel.setMaximizable(true);
        JmainPainel.setMaximumSize(new java.awt.Dimension(480, 420));
        JmainPainel.setMinimumSize(new java.awt.Dimension(480, 420));
        JmainPainel.setPreferredSize(new java.awt.Dimension(480, 420));
        JmainPainel.setVisible(true);

        UserID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserID.setText("User");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Name");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Phone");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Password");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Profile");

        jLabel6.setText("User active");

        jLabel7.setText("Time logged in");

        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });

        cboProfile.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cboProfile.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "admin", "staff", "student" }));

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addDB.jpg"))); // NOI18N

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/searchDB.jpg"))); // NOI18N
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnDrop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delDB.jpg"))); // NOI18N

        btnUpd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/updateDB.jpg"))); // NOI18N

        javax.swing.GroupLayout jInternalFrame3Layout = new javax.swing.GroupLayout(jInternalFrame3.getContentPane());
        jInternalFrame3.getContentPane().setLayout(jInternalFrame3Layout);
        jInternalFrame3Layout.setHorizontalGroup(
            jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame3Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame3Layout.createSequentialGroup()
                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(UserID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtID)
                    .addComponent(txtName)
                    .addComponent(txtPhone, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPass, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cboProfile, 0, 100, Short.MAX_VALUE))
                .addGap(83, 83, 83))
            .addGroup(jInternalFrame3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAdd)
                .addGap(49, 49, 49)
                .addComponent(btnSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnUpd)
                .addGap(34, 34, 34)
                .addComponent(btnDrop)
                .addGap(19, 19, 19))
        );
        jInternalFrame3Layout.setVerticalGroup(
            jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserID)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(cboProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnDrop)
                    .addComponent(btnUpd)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)))
        );

        javax.swing.GroupLayout JmainPainelLayout = new javax.swing.GroupLayout(JmainPainel.getContentPane());
        JmainPainel.getContentPane().setLayout(JmainPainelLayout);
        JmainPainelLayout.setHorizontalGroup(
            JmainPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 464, Short.MAX_VALUE)
            .addGroup(JmainPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JmainPainelLayout.createSequentialGroup()
                    .addGap(0, 232, Short.MAX_VALUE)
                    .addComponent(jInternalFrame3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 232, Short.MAX_VALUE)))
        );
        JmainPainelLayout.setVerticalGroup(
            JmainPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 392, Short.MAX_VALUE)
            .addGroup(JmainPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JmainPainelLayout.createSequentialGroup()
                    .addGap(0, 196, Short.MAX_VALUE)
                    .addComponent(jInternalFrame3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 196, Short.MAX_VALUE)))
        );

        JRegPan.setVisible(true);

        javax.swing.GroupLayout JRegPanLayout = new javax.swing.GroupLayout(JRegPan.getContentPane());
        JRegPan.getContentPane().setLayout(JRegPanLayout);
        JRegPanLayout.setHorizontalGroup(
            JRegPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 464, Short.MAX_VALUE)
        );
        JRegPanLayout.setVerticalGroup(
            JRegPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 392, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        javax.swing.GroupLayout RegPanLayout = new javax.swing.GroupLayout(RegPan);
        RegPan.setLayout(RegPanLayout);
        RegPanLayout.setHorizontalGroup(
            RegPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );
        RegPanLayout.setVerticalGroup(
            RegPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 422, Short.MAX_VALUE)
        );

        RegMenu.setText("Registration");
        RegMenu.setEnabled(false);
        RegMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegMenuActionPerformed(evt);
            }
        });

        RegMenuTab.setText("User registration");
        RegMenuTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegMenuTabActionPerformed(evt);
            }
        });
        RegMenu.add(RegMenuTab);

        jMenuBar2.add(RegMenu);

        StaffReg.setText("Staff");
        StaffReg.setEnabled(false);
        StaffReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StaffRegActionPerformed(evt);
            }
        });

        MenuStaffUpdate.setText("Staff Update");
        MenuStaffUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuStaffUpdateActionPerformed(evt);
            }
        });
        StaffReg.add(MenuStaffUpdate);

        MenuStaffUpdate1.setText("Staff Update");
        MenuStaffUpdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuStaffUpdate1ActionPerformed(evt);
            }
        });
        StaffReg.add(MenuStaffUpdate1);

        jMenuBar2.add(StaffReg);

        examMenu.setText("Lecturer");
        examMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                examMenuActionPerformed(evt);
            }
        });

        AttendanceMenu.setText("Attendance");
        AttendanceMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AttendanceMenuActionPerformed(evt);
            }
        });
        examMenu.add(AttendanceMenu);

        jMenuItem5.setText("Exams ");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        examMenu.add(jMenuItem5);

        jMenuBar2.add(examMenu);

        jMenu5.setText("Student");
        jMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu5ActionPerformed(evt);
            }
        });

        jMenuItem3.setText("Student view");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem3);

        jMenuBar2.add(jMenu5);

        BranchMenu.setText("Branches");
        BranchMenu.setEnabled(false);
        BranchMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BranchMenuActionPerformed(evt);
            }
        });

        DublinMenu.setText("Dublin");
        DublinMenu.setEnabled(false);
        DublinMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DublinMenuActionPerformed(evt);
            }
        });

        jMenuItem8.setText("Student");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        DublinMenu.add(jMenuItem8);

        jMenuItem9.setText("Course");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        DublinMenu.add(jMenuItem9);

        jMenuItem10.setText("Fees");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        DublinMenu.add(jMenuItem10);

        BranchMenu.add(DublinMenu);

        CorkMenu.setText("Cork");
        CorkMenu.setEnabled(false);
        CorkMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorkMenuActionPerformed(evt);
            }
        });

        jMenuItem23.setText("Student");
        jMenuItem23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem23ActionPerformed(evt);
            }
        });
        CorkMenu.add(jMenuItem23);

        jMenuItem24.setText("Course");
        jMenuItem24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem24ActionPerformed(evt);
            }
        });
        CorkMenu.add(jMenuItem24);

        feeCork.setText("Fees");
        feeCork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feeCorkActionPerformed(evt);
            }
        });
        CorkMenu.add(feeCork);

        BranchMenu.add(CorkMenu);

        GalwayMenu.setText("Galway");
        GalwayMenu.setEnabled(false);
        GalwayMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GalwayMenuActionPerformed(evt);
            }
        });

        jMenuItem26.setText("Student");
        jMenuItem26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem26ActionPerformed(evt);
            }
        });
        GalwayMenu.add(jMenuItem26);

        jMenuItem27.setText("Course");
        jMenuItem27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem27ActionPerformed(evt);
            }
        });
        GalwayMenu.add(jMenuItem27);

        GalwayMen.setText("Fees");
        GalwayMen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GalwayMenActionPerformed(evt);
            }
        });
        GalwayMenu.add(GalwayMen);

        BranchMenu.add(GalwayMenu);

        jMenuBar2.add(BranchMenu);

        jMenu7.setText("About");
        jMenuBar2.add(jMenu7);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RegPan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RegPan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(496, 483));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        /*Date date = new Date();
        DateFormat formater = DateFormat.getDateInstance(DateFormat.SHORT);
        lblTimeLogin.setText(formater.format(date));
        lblUser.getText();*/
        
        
    }//GEN-LAST:event_formWindowActivated

    private void StaffRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StaffRegActionPerformed
        // TODO add your handling code here:
         Test_ExamsScreen staffScr = new Test_ExamsScreen();
                    staffScr.setVisible(true);
    }//GEN-LAST:event_StaffRegActionPerformed

    private void jMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu5ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenu5ActionPerformed

    private void RegMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegMenuActionPerformed
         Registration regScr = new Registration();
                    regScr.setVisible(true);
                    RegPan.add(regScr);
        
    }//GEN-LAST:event_RegMenuActionPerformed

    private void RegMenuTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegMenuTabActionPerformed
        Registration regScr = new Registration();
                    regScr.setVisible(true);
                    RegPan.add(regScr);
        
       
    }//GEN-LAST:event_RegMenuTabActionPerformed

    private void MenuStaffUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuStaffUpdateActionPerformed
        // TODO add your handling code here:
        StaffRegistration staffReg = new StaffRegistration();
        staffReg.setVisible(true);
        RegPan.add(staffReg);
    }//GEN-LAST:event_MenuStaffUpdateActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        //Searching();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        StudentScreen stdView = new StudentScreen();
        stdView.setVisible(true);
        RegPan.add(stdView);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        FeesScreen feeScr = new FeesScreen();
        feeScr.setVisible(true);
        RegPan.add(feeScr);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
                // Course
                
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
       StudentEnrol stdEnrol = new StudentEnrol();
        stdEnrol.setVisible(true);
        RegPan.add(stdEnrol);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem23ActionPerformed
      StudentEnrol stdEnrol = new StudentEnrol();
        stdEnrol.setVisible(true);
        RegPan.add(stdEnrol);  // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem23ActionPerformed

    private void jMenuItem24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem24ActionPerformed

    private void feeCorkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feeCorkActionPerformed
        FeesScreen feeScr = new FeesScreen();
        feeScr.setVisible(true);
        RegPan.add(feeScr);        // TODO add your handling code here:
    }//GEN-LAST:event_feeCorkActionPerformed

    private void jMenuItem26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem26ActionPerformed
       StudentEnrol stdEnrol = new StudentEnrol();
        stdEnrol.setVisible(true);
        RegPan.add(stdEnrol); // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem26ActionPerformed

    private void jMenuItem27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem27ActionPerformed

    private void GalwayMenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GalwayMenActionPerformed
     FeesScreen feeScr = new FeesScreen();
        feeScr.setVisible(true);
        RegPan.add(feeScr);    }//GEN-LAST:event_GalwayMenActionPerformed

    private void DublinMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DublinMenuActionPerformed
    //DublinScreen dublinscr =  new DublinScreen
    //dublinscr.setVisible(true)
    //RegPan.add(dublinscr);
    //TODO add your handling code here:
    }//GEN-LAST:event_DublinMenuActionPerformed

    private void CorkMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorkMenuActionPerformed
    //CorkScreen corkscr =  new CorkScreen
    //corkscr.setVisible(true)
    //RegPan.add(corkscr);

        // TODO add your handling code here:
    }//GEN-LAST:event_CorkMenuActionPerformed

    private void GalwayMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GalwayMenuActionPerformed
    
    //GalwayScreen galwayscr =  new GalwayScreen
    //galwayscr.setVisible(true)
    //RegPan.add(galqayscr);

        // TODO add your handling code here:
    }//GEN-LAST:event_GalwayMenuActionPerformed

    private void MenuStaffUpdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuStaffUpdate1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuStaffUpdate1ActionPerformed

    private void AttendanceMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AttendanceMenuActionPerformed
   /* AttendanceScreen attdncScr = new AttendanceScreen();
    attdncScr.setVisible(true);
    RegPan.add(attdncScr);*/
// TODO add your handling code here:
    }//GEN-LAST:event_AttendanceMenuActionPerformed

    private void examMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_examMenuActionPerformed
   // TODO add your handling code here:
    }//GEN-LAST:event_examMenuActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
     ExamsScr examscr = new ExamsScr();
    examscr.setVisible(true);
    RegPan.add(examscr);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void BranchMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BranchMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BranchMenuActionPerformed

////    /**
     /* @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AttendanceMenu;
    public static javax.swing.JMenu BranchMenu;
    public static javax.swing.JMenu CorkMenu;
    public static javax.swing.JMenu DublinMenu;
    private javax.swing.JMenuItem GalwayMen;
    public static javax.swing.JMenu GalwayMenu;
    private javax.swing.JInternalFrame JRegPan;
    private javax.swing.JInternalFrame JmainPainel;
    private javax.swing.JMenuItem MenuStaffUpdate;
    private javax.swing.JMenuItem MenuStaffUpdate1;
    public static javax.swing.JMenu RegMenu;
    private javax.swing.JMenuItem RegMenuTab;
    private javax.swing.JPanel RegPan;
    public static javax.swing.JMenu StaffReg;
    private javax.swing.JLabel UserID;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDrop;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpd;
    private javax.swing.JComboBox<String> cboProfile;
    private javax.swing.JMenu examMenu;
    private javax.swing.JMenuItem feeCork;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPass;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
